# propogate joe and dons passwords for containers and profiles
# HACK HACK. (Not very generalized)

- hosts: kb2018
  gather_facts: false
  become: true  
  tasks:
  - name: Get Joes Hash
    shell: "grep joe /etc/shadow | cut -d: -f2"
    register: joes_hash
  - set_fact:
      joes_pwd: "{{joes_hash.stdout}}"
      cacheable: yes
  - debug: msg="Joes pwd is {{joes_pwd}}"

  - name: Get Dons Hash
    shell: "grep feurig /etc/shadow | cut -d: -f2"
    register: dons_hash
  - set_fact:
      dons_pwd: "{{dons_hash.stdout}}"
      cacheable: yes
  - debug: msg="dons pwd is {{dons_pwd}}"

  - name: Update LXD Profile susdev20 
    shell: "lxc profile show susdev20>/etc/ansible/files/susdev20.profile.yaml "
   
#  - name Updare Dons profile pwd
  - replace:
        path: /etc/ansible/files/susdev20.profile.yaml
        regexp: '(name[^f]*feurig[^p]*passwd[^\"]*\")(.[^\"]*)'
        replace: '\1{{dons_pwd}}'
        backup: yes

#  - name Updare Joes profile pwd
  - replace: 
        path: /etc/ansible/files/susdev20.profile.yaml
        regexp: '(name[^j]*joe[^p]*passwd[^\"]*\")(.[^\"]*)'
        replace: '\1{{joes_pwd}}'
        backup: yes

  - shell: "lxc profile edit susdev20 < /etc/ansible/files/susdev20.profile.yaml"

- hosts: managedbykate
  gather_facts: false
  become: true  
  tasks:
  - name: Update Joes Password
    user:
      name: joe
      update_password: always 
      password: "{{ hostvars['kb2018']['ansible_facts']['joes_pwd'] }}"
  - debug: msg="Updated Joe's Password to {{ hostvars['kb2018']['ansible_facts']['joes_pwd'] }}"

  - name: Update Dons Passowrd
    user:
      name: feurig
      update_password: always 
      password: "{{ hostvars['kb2018']['ansible_facts']['dons_pwd'] }}"
  - debug: msg="Updated Don's Password to {{ hostvars['kb2018']['ansible_facts']['dons_pwd'] }}"
