site_name: D. Delmar Davis

theme:
  name: material
  palette:
    primary: white
    accent: red
  font:
#    text: Courier Prime
    text: JetBrains Mono
#    text: Share Tech Mono
  logo: images/think2t.png.svg
  favicon: images/favicon.png
  features:
    - navigation.expand
    - navigation.tabs

plugins:
    - search
    - with-pdf
    - mermaid2

markdown_extensions:
  - pymdownx.superfences:
        # make exceptions to highlighting of code:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom
